### Get all Todos
GET http://127.0.0.1:8080/v2 HTTP/1.1

### Get Todo by ID
GET http://127.0.0.1:8080/v2/4 HTTP/1.1

### Post new Todo
POST  http://127.0.0.1:8080/v2 HTTP/1.1
Content-Type: application/json

{
    "name": "iiou",
    "description": "jdoiwdowepd"
}

### Update Todo by ID
PUT  http://127.0.0.1:8080/v2/9 HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Todo",
    "description": "Heewlloooo"
}

### Delete Todo by ID
DELETE   http://127.0.0.1:8080/v2/7 HTTP/1.1


### DB test
GET http://127.0.0.1:8080/time HTTP/1.1
