### Get all Todos
GET http://127.0.0.1:3000 HTTP/1.1

### Get Todo by ID
GET http://127.0.0.1:3000/3 HTTP/1.1

### Post new Todo
POST  http://localhost:3000 HTTP/1.1
Content-Type: application/json

{
    "name": "Hello World",
    "description": "Heewlloooo"
}

### Update Todo by ID
PUT  http://localhost:3000/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Hello World",
    "description": "Heewlloooo"
}

### Delete Todo by ID
DELETE   http://localhost:3000/1 HTTP/1.1


### DB test
GET http://localhost:3000 HTTP/1.1

